### ISSUE TITLE
Duplicate view.php for each component

### ISSUE THREAD

**Issue by rbertram90** [timbercms/timbercms#157]
Have noticed under each component there is the duplicated view.php.

As the code is identical for each admin component & front-end component, is it worth changing to have just two classes - one for admin and one for front-end for?

The component name can be passed in the constructor.

**Comment by Smith0r** [comment]
Good point! Makes an unnecessary extra step when creating a new component, and extra un-needed filesize to the main download.
Will assign this to the 2.0 release!
