### ISSUE TITLE
Database ordering field bugs x 2

### ISSUE THREAD

**Issue by rbertram90** [timbercms/timbercms#206]
Noticed a couple of bugs surrounding the ordering field that appears in several db tables

1. articles_categories table - installer/index.php tries to insert value "publish_time DESC" but the field datatype is listed as INT(11)
2. components table - there is no mention of an ordering field but in admin/templates/default/index.php on line 60 it is trying to order by this field

Seen XML files with database setup in recent commits, so guess this might be obsolete soon anyway? 👴

**Comment by Smith0r** [comment]
Ah yeah, the installer is still on my list to sort out!
You're right though, the new database.xml files should fix that issue as the #__components field has an ordering of INT(11) DEFAULT '0' in (admin/components/extensions/database.xml)

I'm attempting to make v2 much more robust in the way it handles database data, check out [this commit](https://github.com/timbercms/timbercms/commit/add47d39e6b82e71e8a7c2a5d4430e7aa66ed798#diff-2cf87f0f9749ec86c03fa9c22e99ecab) for ways i've made models much easier to work with, no more typing out field names for every model! [File for reference of the new model](https://github.com/timbercms/timbercms/blob/add47d39e6b82e71e8a7c2a5d4430e7aa66ed798/admin/components/content/models/article.php)

All fields are loaded and stored using the fields specified in the database.xml of each component, which i'm really excited about!

**Comment by rbertram90** [comment]
Looks a nice step forward 😄 used to work on a system with a similar concept. The implementation in that case was to have one line of XML with attributes for both how it should display on a HTML form and stored in the database.

e.g. `<field name="firstname" type="string" length="50" required="true" default="John" placeholder="First name" />` from that you have enough information to generate SQL server side to create the database field and output a form field.

It then went a step further to allow complex validation criteria and display conditions where a field could be shown or hidden based on another value.

**Comment by Smith0r** [comment]
Hmm, interesting! I'll keep that in mind if it turns out that the current way proves difficult to work with! 😃
