### ISSUE TITLE
Type mismatch on category manager

### ISSUE THREAD

**Issue by rbertram90** [timbercms/timbercms#210]
![screenshot_2018-10-11 timber cms - admin](https://user-images.githubusercontent.com/7643361/46829485-dd372500-cd95-11e8-920c-ecf751f15ec5.png)

**Comment by Smith0r** [comment]
Pretty sure i've now fixed this in the commit above, thanks for reporting!
This also made me realise I probably need to make a setting for the level of error reporting required.
