### ISSUE TITLE
Warning when viewing article

### ISSUE THREAD

**Issue by rbertram90** [timbercms/timbercms#215]
Get the following warning (with error reporting turned on) when viewing an article on the front end

Warning: Invalid argument supplied for foreach() in core\classes\model.php on line 16

**Comment by Smith0r** [comment]
Nice one, thanks! Will add this to the bug fix version 😄

**Comment by Smith0r** [comment]
I believe this one to be related to your other issue #216 
If I comment out line 9 (public $table = "articles";) of components/content/models/article.php the error you described appears!
