### ISSUE TITLE
Validation on unique and protected aliases

### ISSUE THREAD

**Issue by rbertram90** [timbercms/timbercms#217]
Can create two articles with the same alias - would be nice to either have validation, or the system to work out a unique alias. Drupal for example appends a number to the end. So if "about-us" already exists, the alias would be "about-us-0".

Suspect this issue might extend to categories/menu items etc. with the same aliases?

Also nothing to stop someone creating alias that conflict with system ones such as /user or /admin. Again maybe worth saving users from themselves (or someone intentionally pranking the system 😈)

**Comment by Smith0r** [comment]
Oddly enough, this one has been in the back of my mind since I first started work on it, and every release I forget about it! Added to the next version!

**Comment by Smith0r** [comment]
This was actually easier than I thought.
First of all, it checks to see if the alias is a "banned" one, if so, suffixes with "-banned" and explains why it's been changed in a message to the user.
Next, checks if there are any menu items using the alias, if there are, suffixes an index (as per your suggestion).
If no menu items are found, checks for duplicates in the current table and suffixes an index if needed.

As the alias generation is now centralised, any component that uses the alias column name will have a unique alias!
